### PR TITLE
Don't treat errors in aggregates as Go errors

### LINKED ISSUE #305: Incorrect deserialisation of an array with errors
Recently I started to work with RedisTimeSeries which has a [`TS.MADD` command](https://oss.redis.com/redistimeseries/commands/#tsmadd). The specialty of this command is the returned array which can contain both `int64` and `error` because in case of an error it continues the execution. This is not handled correctly in radix. Instead of deserialising each value radix fails at the first error it encounters.

Error:

```
response returned from Conn: unmarshaling message off Conn: ERR TSDB: the key is not a TSDB key
```

Example:

```go
package main

import (
	"context"
	"github.com/mediocregopher/radix/v4"
	"log"
	"testing"
	"time"
)

func TestClient_MAdd(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	client, _ := (radix.PoolConfig{}).New(ctx, "tcp", "localhost:6379")
	err := client.Do(ctx, radix.FlatCmd(nil, "TS.CREATE", "known:key"))
	if err != nil {
		t.Error(err)
	}
	defer client.Do(ctx, radix.FlatCmd(nil, "DEL", "known:key"))
	var val interface{}
	args := []interface{}{
		"known:key", 946684800000, 1,
		"missing:key", 946684800000, 1,
		"known:key", 946684800001, 2,
	}
	err = client.Do(ctx, radix.FlatCmd(&val, "TS.MADD", args...))
	if err != nil {
		t.Error(err)
	}
	log.Println(val)
}
```

I tested the same command with `github.com/go-redis/redis/v8`, `github.com/gomodule/redigo`, and `github.com/joomcode/redispipe`. All three of them deserialises the array correctly (`int64`, `error`, `int64`).

### PR DESCRIPTION
**Pull request by nussjustin**
Possible solution for #305

Fixes #305

### CODE REVIEW

File: resp/resp3/resp.go [hunk 1]
```diff
@@ -2004,6 +2011,17 @@ func unmarshalAgg(prefix Prefix, br resp.BufferedReader, l int64, rcv interface{
 		l *= 2
 	}
 
+	if o == nil || o.TreatErrorsAsValues == false {
```
Comment (mediocregopher) [inline resp/resp3/resp.go]: I don't think opts should ever be nil, so need to check for that.

File: resp/resp3/resp.go [hunk 2]
```diff
@@ -1677,27 +1679,29 @@ func Unmarshal(br resp.BufferedReader, rcv interface{}, o *resp.Opts) error {
...
-	case BlobErrorPrefix:
-		var into BlobError
-		if err := into.UnmarshalRESP(br, o); err != nil {
-			return err
-		}
-		return resp.ErrConnUsable{Err: into}
-	case AttributeHeaderPrefix:
-		if err := DiscardAttribute(br, o); err != nil {
-			return err
+	if o == nil || !o.TreatErrorsAsValues {
```
Comment (mediocregopher) [inline resp/resp3/resp.go]: Again, opts should never be nil (I don't think? you've looked at this code more recently though lol)

**Review by mediocregopher — COMMENTED** [review]
:pray:

File: resp/resp3/resp.go [hunk 3]
```diff
@@ -1609,6 +1609,8 @@ func saneDefault(prefix Prefix) (interface{}, error) {
 	// we don't handle ErrorPrefix because that always returns an error and
 	// doesn't touch I
```
Comment (nerg4l) [inline resp/resp3/resp.go]: This comment might need some addition as errors will be handled here in case of `TreatErrorsAsValues`.

File: resp/resp3/resp.go (hunk 1 above)
Comment (nussjustin) [reply resp/resp3/resp.go]: I just assumed it was ok for it to be nil, but it looks like all the code assumes it's non-nil, so I removed the check.

File: resp/resp3/resp.go (hunk 2 above)
Comment (nussjustin) [reply resp/resp3/resp.go]: Done

File: resp/resp3/resp.go (hunk 3 above)
Comment (nussjustin) [reply resp/resp3/resp.go]: The comment doesn't make much sense with the new code so I removed it.

File: resp/resp.go [hunk 4]
```diff
@@ -50,6 +50,10 @@ type Opts struct {
 	// deterministic results. This is largely used for ensuring map key/values
 	// are emitted in a deterministic order.
 	Deterministic bool
+
+	// TreatErrorsAsValues indicates that unmarshaled RESP errors should
+	// not be treated as actual errors but like other response type.
+	TreatErrorsAsValues bool
```
Comment (nussjustin) [inline resp/resp.go]: Not really happy with the name, but all the others I came up with were even worse.

**Comment by nussjustin** [comment]
This may actually also fix #296 

Not too sure about it, but sounds like it should.

File: resp/resp.go (hunk 4 above)
Comment (nerg4l) [reply resp/resp.go]: What do you think about `DisableErrorBubbling`?

Comment (nussjustin) [reply resp/resp.go]: Ok, let's go with this.

**Comment by mediocregopher** [comment]
This is looking good to me, @nussjustin do you think it's good to go?

**Comment by nussjustin** [comment]
> This is looking good to me, @nussjustin do you think it's good to go?

Yes

**Comment by nerg4l** [comment]
One last detail but this is something which can be handled in user space. If the returned value is not complex and can be casted to an error then it could make sense to return it as an error instead of a value.

**Comment by mediocregopher** [comment]
> One last detail but this is something which can be handled in user space. If the returned value is not complex and can be casted to an error then it could make sense to return it as an error instead of a value.

I think this would unnecessarily complicate the behavior of the flag, especially since (as you said) it could be done in user-space.
